# rnn
name: rnn
input_size: 8
hidden_size: 16 # num of cell states
num_layers: 5
nonlinearity: 'tanh'
bias: true
batch_first: false
dropout: 0.3
bidirectional: false
# Output head
output_head:
  task: classification
  d_out: 1
  d_hidden: null
  activation_output: 'relu'
  reduced: true
  cls_method: autoregressive
